num_lifeforms: 1000
speed:
  min: 1
  max: 1

num_resources: 0

x_position:
  min: 0.
  max: 50.

y_position:
  min: 0.
  max: 50.

resource_availability:
  min: 0
  max: 10

num_interactions:
  consumes: 500
  predatorprey: 900